### ISSUE TITLE
yoast_wpseo_canonical is not correctly fetched

### ISSUE THREAD

**Issue by DAreRodz** [worona/wp-api-yoast-meta#4]
When retrieving a post list, each post has the same `yoast_wpseo_canonical` than the first one on the list.
Look at post with id 2085:

https://blog.worona.org/?rest_route=/wp/v2/posts

If you retrieve a single post, that property is correctly set.

https://blog.worona.org/?rest_route=/wp/v2/posts/2085

**Comment by Poliuk** [comment]
I'm unable to force Yoast plugin to give me the correct values. So we have to remove the field `yoast_wpseo_canonical` for the moment.

@orballo before I remove it from the plugin, can you confirm if we are using it somewehere?

**Comment by orballo** [comment]
Regarding the fields `yoast_wpseo_homepage_title` and `yoast_wpseo_homepage_metadesc`, they aren't being used. Those values are taken from `?rest_route=/wp/v1/site-info`.

But the fields `yoast_wpseo_title`, `yoast_wpseo_metadesc`, and `yoast_wpseo_canonical` are being used in https://github.com/worona/wp-org-connection-app-extension-worona/blob/50fbe0f578d611bc8d2501e6aa07b06e0be35c86/src/pwa/selectors/index.js#L54-L81, with fallbacks to other fields if these don't exist.

**Comment by Poliuk** [comment]
Solved thanks to the contributions of @niels-garve (https://github.com/niels-garve/yoast-to-rest-api) now merged to this plugin

**Comment by luisherranz** [comment]
Thanks for figuring this out @niels-garve! We owe you a beer 🍻  😁

**Comment by niels-garve** [comment]
Thanks @luisherranz and @Poliuk - you're very welcome! :D
Btw, I tried to "pull request" my/our changes back to the original repository - without success...I thought it would be nice to update the WordPress plugin with all our work.
Maybe we could re-submit a new plugin? What do you think?

**Comment by Poliuk** [comment]
Hey @niels-garve, thanks a lot for your help!

We created the fork because we need this plugin as a complement to our main plugin [WordPress PWA](https://wordpress.org/plugins/wp-pwa/). We have submitted the v1.5.0 of this repo to the WordPress repository, the plugin will be called **"Yoast SEO for WordPress PWA"**, should be live today.

As you can see [here](https://github.com/wp-pwa/yoast-seo-for-wp-pwa/blob/master/yoast-seo-for-wp-pwa.php#L36) & [here](https://github.com/wp-pwa/yoast-seo-for-wp-pwa/blob/master/utils/get_site_info.php), we need to include some filters to interact with our main plugin.

I don't know if it make sense for you to use our version, or you prefer to publish your fork. It will be really interesting to work together, but we have to include the code to interact with the main plugin. Let us know what you think!

**Comment by luisherranz** [comment]
I think the best approach would be to have two separate repositories (yours and ours) and watch each other to merge each other changes when convenient. We've merged your changes and we kept your new naming, so merging changes would be easy in the future.

And I think you should upload your own plugin to the repository for those using only Yoast and the WP-API and not our plugin. I bet it'll be quite popular :)

We've named our "Yoast SEO for WordPress PWA" and you can name yours "Yoast to REST API". I think people won't confuse them that way.

**Comment by niels-garve** [comment]
Thanks for your thoughts @Poliuk and @luisherranz !
Okay, lets watch our repositories and update them, whenever there's something new; and I'll think about submitting an own plugin...last thought on this: how about making a settings page where you can enable/disable the integration to wp pwa? not satisfying though...I feel two plugins and two code basis aren't either?
(https://codex.wordpress.org/Creating_Options_Pages)

**Comment by luisherranz** [comment]
If you don't mind having an option to enable/disable the wp pwa integration, then let's work on a single repository/plugin. If you do, then we'll work on separate repositories and plugins and we'll try to merge changes.

It's up to you. We are fine with either decision :)

**Comment by luisherranz** [comment]
By the way, if you want to go with the single plugin option, we can create the initial options page.
